2019-12-03 21:38:58,658 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:39:01,791 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:39:26,153 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:39:29,799 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:39:55,691 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:39:58,843 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:44:33,328 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:44:43,964 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:46:19,580 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:47:13,576 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-06 19:21:03,472 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-06 19:21:06,551 ERROR: Exception on /login [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\login.html", line 2, in <module>
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\login.html", line 17, in root
    {% endblock %}
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 21, in root
    <span class="icon-bar"></span>
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 64, in block_navbar
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'field' is undefined
