2019-12-03 21:24:17,566 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:27:39,577 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:27:45,305 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:28:00,059 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:28:02,623 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:28:23,263 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:28:26,381 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:28:48,914 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:28:52,535 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:28:56,044 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:29:56,906 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:30:02,339 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:30:06,645 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'username'
2019-12-03 21:32:03,420 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:34:54,969 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
